services:
  db:
    image: postgres:16-alpine
    container_name: taskmanager-db
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U taskuser -d taskdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: taskmanager-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: prod
      DB_URL: jdbc:postgresql://db:5432/taskdb
      DB_USERNAME: taskuser
      DB_PASSWORD: taskpass
      DB_DRIVER: org.postgresql.Driver
      FLYWAY_ENABLED: "true"
      JPA_DDL_AUTO: validate
      SERVER_PORT: "8080"
      # CORS origin per Angular (porta 4200), se gestisci via variabile in config custom
      # CORS_ALLOWED_ORIGINS: http://localhost:4200
    ports:
      - "8080:8080"

volumes:
  pgdata:
