services:
  db:
    image: postgres:16-alpine
    container_name: taskmanager-db
    environment:
      POSTGRES_DB: taskdb
      POSTGRES_USER: taskuser
      POSTGRES_PASSWORD: taskpass
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL","pg_isready -U taskuser -d taskdb"]
      interval: 5s
      timeout: 3s
      retries: 10

  app:
    build: .
    container_name: taskmanager-app
    depends_on:
      db:
        condition: service_healthy
    environment:
      SPRING_PROFILES_ACTIVE: dev
      SPRING_DATASOURCE_URL: jdbc:postgresql://db:5432/taskdb
      SPRING_DATASOURCE_USERNAME: taskuser
      SPRING_DATASOURCE_PASSWORD: taskpass
      SPRING_DATASOURCE_DRIVER_CLASS_NAME: org.postgresql.Driver
      SPRING_FLYWAY_ENABLED: "true"
      SPRING_JPA_HIBERNATE_DDL_AUTO: validate
      SERVER_PORT: "8080"
      # DevTools configurazione per hot reload
      SPRING_DEVTOOLS_RESTART_ENABLED: "true"
      SPRING_DEVTOOLS_LIVERELOAD_ENABLED: "true"
      SPRING_DEVTOOLS_RESTART_POLL_INTERVAL: "1000"
      SPRING_DEVTOOLS_RESTART_QUIET_PERIOD: "400"
      # CORS origin per Angular (porta 4200), se gestisci via variabile in config custom
      # CORS_ALLOWED_ORIGINS: http://localhost:4200
    ports:
      - "8080:8080"
    volumes:
      # Monta tutto il codice sorgente per hot reload automatico
      - ./src:/app/src
      # Monta la directory target per le classi compilate
      - ./target:/app/target
      # Cache Maven per velocizzare i build
      - maven-cache:/root/.m2

volumes:
  pgdata:
  maven-cache:
