server:
  port: ${SERVER_PORT:8080}

spring:
  datasource:
    url: ${DB_URL:jdbc:h2:mem:proddb;MODE=PostgreSQL;DATABASE_TO_LOWER=TRUE}
    username: ${DB_USERNAME:sa}
    password: ${DB_PASSWORD:}
    driver-class-name: ${DB_DRIVER:org.h2.Driver}
  jpa:
    hibernate:
      ddl-auto: ${JPA_DDL_AUTO:update}
    open-in-view: false
  flyway:
    enabled: ${FLYWAY_ENABLED:true}

management:
  endpoints:
    web:
      exposure:
        include: health,info
